import { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { QueryProvider } from "@/shared/providers/QueryProvider";
import { ProtectProvider } from "@/shared/providers/ProtectProvider";
import "@/app/styles/globals.scss";

export const metadata: Metadata = {
  title: "DJ",
  description: "Generated by create next app",
};

const Merriweather = localFont({
  src: [
    {
      path: "../public/fonts/Merriweather/Merriweather-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Bold.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Black.woff2",
      weight: "600",
      style: "normal",
    },
  ],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" className={Merriweather.className}>
      <body>
        <QueryProvider>
          <ProtectProvider>{children}</ProtectProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
