import type { Metadata } from "next";
import "@/app/styles/globals.scss";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "GR",
  description: "Generated by create next app",
};

const Merriweather = localFont({
  src: [
    {
      path: "../public/fonts/Merriweather/Merriweather-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Bold.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Merriweather/Merriweather-Black.woff2",
      weight: "600",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={Merriweather.className}>
      <body>
        {/*<Providers session={session}>{children}</Providers>*/}
        {children}
      </body>
    </html>
  );
}
